### ISSUE TITLE
Wrap config reading in path resolution

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/datasetdatabase#17]
B/c 
`prod = dsdb.DatasetDatabase(config="~/.dsdb_prod.json")`
gives me
`FileNotFoundError: [Errno 2] No such file or directory: '~/.dsdb_prod.json'`
despite the presence of that file in my home dir.

**Comment by JacksonMaxfield** [comment]
Update to v1.0.3 this has been resolved. `~` is both expanded to user, and all paths are resolved.
